import type { Metadata } from "next";
import { inter } from "@/lib/fonts";
import "./globals.css";
import TanstackProvider from "@/lib/providers/TanstackProvider";
import ReduxProvider from "@/lib/providers/ReduxToolkitProvider";
import NavBar from "@/components/NavBar";
import MobileNavBar from "@/components/MobileNavBar";
import Footer from "@/components/sections/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <TanstackProvider>
          <body
            className={`${inter.className} antialiased relative min-h-screen`}
          >
            {<MobileNavBar />}
            <NavBar />
            {children}
            <Footer />
          </body>
        </TanstackProvider>
      </ReduxProvider>
    </html>
  );
}
