import type { Metadata } from "next";
import { inter } from "@/lib/fonts";
import "./globals.css";
import TanstackProvider from "@/lib/providers/TanstackProvider";
import ReduxProvider from "@/lib/providers/ReduxToolkitProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <TanstackProvider>
          <body className={`${inter.className} antialiased`}>{children}</body>
        </TanstackProvider>
      </ReduxProvider>
    </html>
  );
}
